CREATE SCHEMA IF NOT EXISTS CQRS;

CREATE TABLE IF NOT EXISTS CQRS.EVENT(
	ID VARCHAR(36) UNIQUE NOT NULL,
	VERSION BIGINT AUTO_INCREMENT NOT NULL,
	TYPE VARCHAR(300) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	CREATOR VARCHAR(500) NOT NULL,
	AGGREGATE_ID VARCHAR(36) NOT NULL,
	PAYLOAD CLOB NOT NULL,
	IGNORED BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_EVENT PRIMARY KEY (ID),
	CONSTRAINT FK_AGGREGATE FOREIGN KEY (AGGREGATE_ID) REFERENCES AGGREGATE(ID),
	CONSTRAINT UC_VERSION UNIQUE (AGGREGATE_ID, VERSION)
);

CREATE TABLE IF NOT EXISTS CQRS.AGGREGATE(
	ID VARCHAR(36) UNIQUE NOT NULL,
	VERSION BIGINT AUTO_INCREMENT NOT NULL,
	TYPE VARCHAR(300) NOT NULL,
	LAST_UPDATED TIMESTAMP NOT NULL,
	CONSTRAINT PK_AGGREGATE PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CQRS.SNAPSHOT(
	ID VARCHAR(36) UNIQUE NOT NULL,
	VERSION BIGINT AUTO_INCREMENT NOT NULL,
	AGGREGATE_ID VARCHAR(36) NOT NULL,
	STATE CLOB NOT NULL,
	CONSTRAINT PK_SNAPSHOT PRIMARY KEY (ID)
);